### ISSUE TITLE
Brightness Slider Widget Issue

### ISSUE THREAD

**Issue by ediskrad73** [fifafu/BetterTouchTool#1366]
#### Description of bug/feature request/question:
The brightness slider widget will not go to the "full" position. The display overlay shows it is all the way up, but the slider will not stop at the full right position. Screenshot below.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 2017 15" MacBook Pro
macOS version: 10.13 High Sierra Public Beta 17A352a
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Screenshot:

<img width="1085" alt="touch bar shot 2017-08-23 at 4 38 13 pm" src="https://user-images.githubusercontent.com/22204514/29637444-1fa60e98-8822-11e7-8207-f2a7c3fc8bf4.png">

**Comment by fifafu** [comment]
This should be fixed in the most recent version.

**Comment by BradleyGKV** [comment]
<img width="1085" alt="touch bar shot 2018-04-26 at 10 02 27 pm" src="https://user-images.githubusercontent.com/34726304/39342420-9cde3880-499d-11e8-9991-f97df101b0c2.png">
Still an issue for me in v2.444

**Comment by fifafu** [comment]
Unfortunately in your case it's an issue with custom knob images.
The Touch Bar only allows one size of "Knob" which is pretty big why BTT adds a small "padding". However this causes the issue you describe.
I'll add an option to draw the image without padding, however that causes the knob to be pretty big.

**Comment by BradleyGKV** [comment]
Thanks for adding this feature so quickly! I have one quick question for you though. What are the "correct" dimensions for a custom slider image? Meaning, what are the dimensions for a slider that would fill the image area without the need for padding? I hope that makes sense.
