### ISSUE TITLE
Siri remote keeps disconnecting after the macOS 10.12.2 upgrade

### ISSUE THREAD

**Issue by soloristretto** [fifafu/BetterTouchTool#153]
After my mac upgraded to macOS 10.12.2, I keep losing connection of the BetterTouchTool to my Siri remote. However if I go into Bluetooth settings of the computer and press any button on the remote, I get reconnected. After a bit (I think after the mac sleeps, I have the same problem again. Anything I can do to fix this problem?

**Comment by tnaz** [comment]
i have the same problem. sometimes it disconnects after a period of inactivity, sometimes it disconnects randomly, and sometimes its just slow to respond. it will at times connect by just touching a button on the remote, but majority of the time it needs to connect by opening bluetooth preferences, where it will then be recognized. i won't have to do anything more than hit a button most of the time while bluetooth preferences are open for it to reconnect.

**Comment by soloristretto** [comment]
yes, @tnaz describes my problem precisely. I used to also have SiriMote app working alongside the BetterTouchTool (it provides a few options on top of what BTT offers) but SiriMote ceased working with BTT long time ago, after one of BTT updates. The combination of SiriMote and BTT was really awesome. Sad...

**Comment by fifafu** [comment]
Mhh that's unfortunate as this is completely handled by the system.
It is normal that the remote disconnects (to save battery), however it should reconnect as soon as pressing a button on it.

Also @soloristretto , BTT needs to claim full control over the Siri Remote since Sierra due to changes made by Apple. Thus it's not possible anymore to have two apps using the Siri Remote at the same time anymore. What were you using Siri Remote for?

**Comment by tnaz** [comment]
@fifafu i also had sirimote installed, but was not using it. i have uninstalled it and am still having these issues. do you think this issue is specific to a conflict between btt and sirimote? and if so, is it possible that even after uninstalling sirimote there is a conflict persisting?

**Comment by fifafu** [comment]
@tnaz no I don't think SiriRemote can interfere (at least if it's not running). It sounds more like a macOS bug. I'll try to reproduce it later today!

**Comment by fifafu** [comment]
I think the issue has been resolved with the latest 10.12.3 beta, at least it hasn't happened for me anymore.

**Comment by soloristretto** [comment]
Thanks for this @fifafu. I upgraded to 10.12.3 beta and It seems working now though it did happen to me once. Anyway I'll keep watching it... If the problem happens again, I'll post it here.

**Comment by soloristretto** [comment]
@fifafu To follow this up. Still the same issue, even on 10.12.3 beta, maybe slightly less often. In order to have the Siri Remote work I have to go into bluetooth settings and then press a button on the remote. Otherwise pressing the remote doesn't do anything.

**Comment by fifafu** [comment]
I can also still reproduce the issue. However I have noticed that long pressing the "menu" button seems to reconnect the Siri Remote, could you check if this also works for you?

**Comment by tnaz** [comment]
that seems to work sometimes. often does not. also, frequent disconnects or delayed responses.

**Comment by soloristretto** [comment]
@fifafu same as per @tnaz message

**Comment by tnaz** [comment]
update: a few days ago i deleted all bluetooth devices from my computer and then reset the bluetooth module. the siri remote was connecting seamlessly for about 2 days with no interruption, but the problem has come back. just thought i'd share to see to see if anyone has any insight into this.

**Comment by fifafu** [comment]
So I'm not sure if I accidentally fixed this with version 2.04 or if Apple fixed a bluetooth issue in the 10.12.4 beta, however I haven't encountered the issue for multiple days now. Can anybody confirm that?

**Comment by fifafu** [comment]
This definitely seems to be fixed in 10.12.4, thus I'm closing here. (I think 10.12.4 might be publicly released today)
