### ISSUE TITLE
All items unresponsive when clicking within only the iTunes app 

### ISSUE THREAD

**Issue by knoddix** [fifafu/BetterTouchTool#216]
Description : All items unresponsive when clicking within only the iTunes app (multiple clicks on an option in iTunes forces it to activate said option) This issue disappears immediately after quitting BTT.

**What kind of Mac are you using?** multiple iMacs (mid 2011 27 inch, late 2012 21.5 inch)

**Which input device : Magic Mouse 1st Gen, issue does not occur with Logitech wireless mouse with separate USB bluetooth dongle or USB Microsoft Mouse.

**Which versions of macOS and BetterTouchTool are you running?**  1.963 but the issue has occurred with at least the last 5 updates and issue has persisted from MacOS 10.12 to 10.12.2 I can't recall if the issue happened prior to 10.12.

**Other information:**please find a system report of one of the iMacs here https://www.dropbox.com/sh/t5vzwnabqvohv1w/AABC4cPOSX2DhQqkcRvgNEgQa?dl=0 you will also find a video demonstrating the issue.

Note: In case of bugreports, restart has been performed I have also performed an erase and install of MacOS and then setup the mac without restoring anything and then installed just MacOS Updates and BTT and the issue persists.

**Comment by fifafu** [comment]
Thanks for reporting! I can reproduce it with my Magic Mouse, however I do not yet know what's causing it. iTunes must be doing some very strange stuff. I'll look into it!

**Comment by knoddix** [comment]
Thanks for the tip mate I was unaware of that option that'll definitely do the trick for now.

**Comment by fifafu** [comment]
After more investigation, this definitely seems to be an iTunes bug. I'm reporting it to Apple and hope they'll fix it soon. As far as I can currently tell it only affects Magic Mouse users.

**Comment by knoddix** [comment]
Coming from someone who does tech support for them I wouldn't hold my breath on that lol thanks for looking into it though I appreciate it I will just use the work around mate its really no bother the only shortcut I could see myself in iTunes itself anyway is is 3 finger tap to zoom in but I can always make another apps window active then and then do the 3 finger tap either that or stop being lazy sitting in the bean bag and get closer to the screen haha. FYI I'll file some feedback with work as well generally the more requests submitted for something the more likely engineering is to do something about it.

**Comment by fifafu** [comment]
I think this has been fixed in the current iTunes versions on High Sierra at least.

**Comment by ntorring** [comment]
I'm still experiencing this bug on High Sierra 10.13 and iTunes 12.7.0.166. I was really looking forward to this bug going away, even disabling BTT for iTunes does nothing.

**Comment by fifafu** [comment]
Weird I haven't seen it since Sierra.  :-(

**Comment by ntorring** [comment]
It only seems to be an issue when i'm using my Magic Mouse 1 (Have not tried with 2nd gen)

**Comment by ntorring** [comment]
I've switched to the alpha version of BTT, and it seems to have fixed this bug for me. Could it be related to the workaround for the Chrome bug?
