### ISSUE TITLE
Issue with KeySequences after update from 2.340 to 2.400

### ISSUE THREAD

**Issue by craftey** [fifafu/BetterTouchTool#2213]
Key sequence like 
`CMD, CMD`
to trigger a shortcut like 
`CMD + CTRL + F1`

With version 2.340 the shortcut got triggered successfully.
With version 2.400 the shortcut is not triggered anymore.

Expected:
Behavior of 2.340.

#### Device information:

Type of Mac: MacBook Pro 13 Touchbar + external magic keyboard
macOS version:  10.13.3
BetterTouchTool version: 2.400

Kindly,
craftey

**Comment by craftey** [comment]
Related to: https://github.com/fifafu/BetterTouchTool/issues/2185

**Comment by craftey** [comment]
Workaround: Reverting to 2.340 with help of Time Machine. The behavior is back to normal then.

**Comment by fifafu** [comment]
Key Sequences should not be affected by #2185 - if possible try to disable & reenable the permissions in System Preferences => Security & Privacy => Privacy => Accessibility. Sometimes macOS doesn't attach them to new versions.

**Comment by craftey** [comment]
Disable & enable `System Preferences => Security & Privacy => Privacy => Accessibility` did not change the initially described behavior of 2.400.

What actually helped with 2.400: `BTT -> Advanced Settings -> "Use old keyboard short implemenation"` https://github.com/fifafu/BetterTouchTool/issues/2185#issuecomment-371930400

**Comment by fifafu** [comment]
That's interesting. This shouldn't affect key sequences. Could you check whether it continues to work when you disable that again?

**Comment by craftey** [comment]
Right after unchecking the option, the key seq still triggers the defined shortcut. But when I restart BTT this disabling actually got into effect and consistently let the definition of the said key seq fail.

By the way the to be triggered shortcut itself is a short cut defined in BTT to trigger some other action. See following picture with the relevant config:
![btt_v2400_issue_key_seq](https://user-images.githubusercontent.com/17045396/37285341-0ea51adc-25ff-11e8-93b2-d4709c6a4f59.png)

**Comment by fifafu** [comment]
I have fixed a bug/logic change in 2.402, would be great if you could check that version.

**Comment by craftey** [comment]
Two times in a row I got:
![bildschirmfoto 2018-03-13 um 08 19 01](https://user-images.githubusercontent.com/17045396/37327652-80f2fa6c-2697-11e8-9259-dffa115d8030.png)
Each time after restart no update was applied.

**Comment by craftey** [comment]
I installed 2.403 manually, after the in-place update for that version also failed like above. However, disabling the option `Use old keyboard short implementation` still disables my key sequence.

**Comment by craftey** [comment]
Recorded key codes with Karabiner-EventViewer which comes with https://pqrs.org/osx/karabiner/

`CMD, CMD`
`Use old keyboard short implementation` disabled 
```
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd
eventType:FlagsChanged    code:0x37       name:left_command    flags:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Ctrl
eventType:KeyDown         code:0x7a       name:f1              flags:Ctrl Cmd Fn
eventType:KeyUp           code:0x7a       name:f1              flags:Fn
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Cmd
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl
eventType:FlagsChanged    code:0x3b       name:left_control    flags:
eventType:FlagsChanged    code:0x37       name:left_command    flags:
```

`CMD, CMD`
`Use old keyboard short implementation` enabled
```
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd
eventType:FlagsChanged    code:0x37       name:left_command    flags:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Ctrl
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Cmd
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl
eventType:FlagsChanged    code:0x3b       name:left_control    flags:
eventType:FlagsChanged    code:0x37       name:left_command    flags:
```

`CMD+CTRL+F1`
`Use old keyboard short implementation` both settings
```
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Ctrl
eventType:FlagsChanged    code:0x3f       name:fn              flags:Ctrl Fn
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Cmd Fn
```

Tested on MacBook Pro 13 Touchbar. Tomorrow I will test the same with the Magic Keyboard.

**Comment by fifafu** [comment]
@craftey no need to test, I have found the issue. (related to F-Keys being triggered by other BTT shortcuts).

Will release a little fix tomorrow :-)

**Comment by craftey** [comment]
After looking at the 1st attempt above I also tried the "On down" option for the shortcut `CMD+CTRL+F1`. It did not fix the `CMD, CMD`-action. But what I found then was also surprising: Hitting now the shortcut `CMD+CTRL+F1` directly seems to trigger its action twice, once on key down and once on key up. I would have expected only once on key down. This happens independently from the setting of `Use old keyboard short implementation`.

**Comment by fifafu** [comment]
https://bettertouchtool.net/releases/btt2.404.zip this version should fix the f key issue. (Going to sleep now, will put together an official update sometime tomorrow)

**Comment by craftey** [comment]
I can confirm 2.404 fixes the issue. Thank you. 👍

**Comment by craftey** [comment]
Btw I still get the Error screen when updating. Now update from the above downloaded zip to newly released 2.405 gave that error.
![bildschirmfoto](https://user-images.githubusercontent.com/17045396/37327652-80f2fa6c-2697-11e8-9259-dffa115d8030.png)

**Comment by fifafu** [comment]
Sounds like some file permission error. Where do you have the BetterTouchTool app located?

**Comment by craftey** [comment]
Typically in `~/Applications`. Updates used to work before, it started failing after 2.400.

**Comment by fifafu** [comment]
Haven't had any other report of update issues (and most users have already updated), thus I assume this is just some weird file permission problem. I'd try to delete it and download a fresh copy.

**Comment by craftey** [comment]
Well I can reproduce the issue with the above zip.
1. downloading the zip unpack it in to my folder. 
2. start the btt 2.404,
3. update btt to 2.4.05 --> fail

So I would say something in my prefs might be broken. Are there any logs I could look at?

**Comment by fifafu** [comment]
Unfortunately not, this is all handled by the sparkle auto updater (if you can ready code, it seems to fail in line 538:  https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUBasicUpdateDriver.m )

However there is nothing really fancy happening. Have you already restarted your machine since?

**Comment by craftey** [comment]
Yupp, line 538 seems solid. I ll try the reboot ...

**Comment by fifafu** [comment]
Otherwise just download the 2.405 from my website, the zip posted here was just a "out of the loop" build, maybe some code signing stuff got screwed up there ;-)

**Comment by craftey** [comment]
The issue started before 2.404. First time was, when I tried to update from 2.400 to 2.403. Anyway, I will do the manual installation of 2.405 now. I will come back, if next update after 2.405 still fails this way. Cheers, and good n8. :)

**Comment by craftey** [comment]
I forgot to say: the reboot did not help.

**Comment by craftey** [comment]
Trashing the folder `~/Library/Caches/com.hegenberg.BetterTouchTool` fixed the sparkle updater. 😊
