### ISSUE TITLE
TouchBar of BTT on system start

### ISSUE THREAD

**Issue by sagitt** [fifafu/BetterTouchTool#33]
after system boot, BTT show our touchbar and there is no option to disable this.

**Comment by fifafu** [comment]
Hey,

If you don't want to use the Touch Bar  features of BTT, you can disable them either in the standard BTT Preferences or in the general Touch Bar settings.

Doesn't this work for you?

**Comment by sagitt** [comment]
Ho, I want use it but I want enable it manually by right button, not that it show the  touch bar of BTT at start

Inviato dal mio iPhone!

**Comment by andrewatwood** [comment]
+1 for this - I want to only toggle it on occasion but every time I wake the machine from sleep the bar shows up whether or not it was previously toggled. If it would just remember the previous setting that would be great!

**Comment by sagitt** [comment]
Exactly the same problem. Maybe an option for this that on start I can enable or disable the auto show

**Comment by fifafu** [comment]
Understood - will fix this with the next update!

**Comment by shadow7840** [comment]
+1, same problem when waking my laptop. Thanks for addressing it, Andreas. btw, used Better Snap for a long time, but I've been trying BTT and the TouchBar customization for a few days. I LOVE IT. Completely worth the recommended price. Thanks so much for giving us this functionality!

**Comment by fifafu** [comment]
Fixed in 1.964 alpha, it now remembers it's last state

**Comment by andrewatwood** [comment]
@fifafu - still getting random re-openings of the Touch Bar where it doesn't respect the previous state. Almost always on Wake but also seems sort of sporadic based on app switching as well. On the latest alpha.

**Comment by sagitt** [comment]
Same problem

**Comment by fifafu** [comment]
Interesting, are you using app specific touchbar settings? (E.g let BTT hide it for specific apps?)
