### ISSUE TITLE
TouchBar Longpress on "Escape" button toggles some strange "globe" button

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#412]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
<img width="1127" alt="screenshot 2017-02-05 13 41 43" src="https://cloud.githubusercontent.com/assets/24585031/22626209/da15d2e8-eba8-11e6-8f9a-1665e91356f2.png">

I have mapped a touchbar key to press the Escape Key. When i long press the button, it will add a new touchbar button on the left with a globe icon and i do not know where its coming from or what its for. I'd like to remove that, is this possible?

Here is a video of the problem:
https://www.dropbox.com/s/7jg1d74k67m3cap/IMG_3363.MOV?dl=0

**What kind of Mac are you using?**
MacBook Pro 2016 w TouchBard 

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
TouchBar

**Which versions of macOS and BetterTouchTool are you running?**
Mac OS 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by aaronweewee** [comment]
OO i have a similar issue, but its not just the esc key, its long pressing any button on icons that stick to the left, I've also just posted an issue regarding this

**Comment by fifafu** [comment]
hey, thanks for reporting, that's a copy & paste bug :-) (the globe should only appear when long-pressing the BTT icon in the control stip.)

I'll fix it with the next update.

**Comment by fifafu** [comment]
should be fixed in 2.021 alpha!

**Comment by fantaaaaaa** [comment]
Yupp, fixed! Thanks!

**Comment by el-lsan** [comment]
Still happening! (Version 2.636):

![image](https://user-images.githubusercontent.com/1249548/46013175-c3c28780-c0cb-11e8-87a8-97cee7a214f4.png)
