### ISSUE TITLE
Touchbar Bug:  Several Commands no longer work in 2.07...reverted to previous version

### ISSUE THREAD

**Issue by rwross1776** [fifafu/BetterTouchTool#496]
MacBook Pro 15" Touchbar

Both grouped and ungrouped commands no longer function however AppleScript sill does.

Tested "Screen Lock" and CMD Shift Del (to empty trash), and empty trash command.

Reverted to previous version and all functions work again

**Comment by pbrentlinger** [comment]
Sound button has failed for me with this version

**Comment by pbrentlinger** [comment]
@rwross1776 How did you revert to the previous version?

**Comment by rwross1776** [comment]
I receive a question about how to revert.  When updating, BTT places the previous version in the trash with appended with a build number.  To revert, delete the current version from you Applications folder.  Move the previous version from Trash to Applications folder and remove the appended build number.

Alternatively, you could restore via Time Machine.

Hope this helps.

**Comment by fifafu** [comment]
Thanks for reporting! should be fixed in 2.071.

**Comment by rwross1776** [comment]
Thanks...this seems to be only partially fixed or could be a limitation of the existing Touchbar functionality.

Use Case:
Global Touchbar button made to empty trash (could be anything)  SHFT CMD Del
Function ONLY works if Finder is in focus.  With any other app in focus, the button does not fire.

However, if a predefined action is used, the function fires regardless of what app has focus.

The question is why do Custom Keyboard Shortcuts and Predefined Actions function in different ways and is this a bug or a limitation.

**Comment by fifafu** [comment]
that's weird, I would think this shortcut in any case only works when Finder is active as it is a Finder shortcut.

However you can use the predefined action "Send shortcut to specific application" and send that shortcut to Finder (which is located in  /System/Library/CoreServices/Finder.app )

**Comment by rwross1776** [comment]
Great workaround...thanks!
