### ISSUE TITLE
Multiple clicks registered when pressure setting below 100

### ISSUE THREAD

**Issue by notsosuperman** [fifafu/BetterTouchTool#84]
I've brought down the pressure needed to register a normal click in the BTT Trackpad settings to more emulate what the the clickable trackpads felt like. However, when the force is brought to below 100, BTT sometime registers multiple clicks with one actual click. To reproduce, bring force for 3 finger normal click to 80, then open live view and slowly try to perform a 3-finger click. You will often feel multiple haptic feedbacks and see that the live view registers multiple clicks. Once you have the pressure at 100 or above, this does not seem to be an issue.

**What kind of Mac are you using?**
2016 15" MBP

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Built-in Trackpad

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Running 1.963

Thanks!

**Comment by pallavmac** [comment]
For me, when setting is below 100, after 1 click, BTT crashes.

**Comment by fifafu** [comment]
Thank you! I'll change the minimum value to 100!

Best,
Andreas

**Comment by fifafu** [comment]
Fixed in 1.964 alpha

**Comment by notsosuperman** [comment]
It looks like this is still happening, though not as frequently. I have force set to 110 for three finger clicks and occasionally have it double click. I don't know that 100 was a magic number, it just seemed to happen more frequently below that. Is there any way to track down and find the root of the cause to allow for these lower settings so that the force required to do three and four finger clicks is consistent with the mechanical trackpads? Thanks!

**Comment by fifafu** [comment]
Hey,

No currently not.
The default values prevent double clicks, setting lower values can lead to the faulty behavior (but depends on the trackpad).

Improving this is complicated, but I'll look into it for future versions.
