### ISSUE TITLE
new tabs open twice

### ISSUE THREAD

**Issue by dargilboa** [fifafu/BetterTouchTool#989]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

after the latest update, whenever I open a new tab using a shortcut it opens twice

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic mouse

#### Device information:

Type of Mac: pro 2016
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
How did you configure your shortcut? Have you tried to restart your mac?

If possible please select the table row with the shortcut you configured in BTT, then press CMD+C and then paste the content BTT has copied to your clipboard here.

**Comment by fifafu** [comment]
I think it should be fixed in v2.16 alpha.

**Comment by dargilboa** [comment]
still not working, I tried restarting and updating to 2.16. Here's the row:
{
  "BTTTriggerType" : 21,
  "BTTTriggerTypeDescription" : "3 Finger Click",
  "BTTTriggerClass" : "BTTTriggerTypeMagicMouse",
  "BTTPredefinedActionType" : 149,
  "BTTPredefinedActionName" : "CMD(⌘)+Double Click (Open in New Finder Tab)",
  "BTTEnabled" : 1,
  "BTTOrder" : 2
}

**Comment by dargilboa** [comment]
just updated to 2.20, this didn't help either

**Comment by fifafu** [comment]
Mh I can't seem to reproduce this. Are you sure it's opening the same tab twice?
Or are you maybe opening two separate folders in new tabs? (this happens if you have one folder selected in Finder, then three finger click on another folder).

**Comment by dargilboa** [comment]
I’m sure, this happens in chrome not Finder.

**Comment by fifafu** [comment]
Wait, this action is specifically for Finder (that's why it says "Open new tab in Finder" :-))
For Chrome or Safari just use the middle-click or the normal cmd-click action!

**Comment by dargilboa** [comment]
Oh thanks, that solved it :)
